version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rails_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
