version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
